theme: jekyll-theme-primer
repository: sdsc-ordes/nixos-workshop
markdown: GFM

plugins:
  - jekyll-gfm-admonitions

kramdown:
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: table
    bold_every: 5

include:
  - README.md
